#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====

export PANGEO_ENV="default"
if ! [[ -z "${PANGEO_SCRATCH_PREFIX}" ]] && ! [[ -z "${JUPYTERHUB_USER}" ]]; then
    export PANGEO_SCRATCH="${PANGEO_SCRATCH_PREFIX}/${JUPYTERHUB_USER}/"
fi

if [[ ! -f /home/user/.tutorial_initialized ]]; then
  cp -rp /srv/tutorials /home/user
#  touch /home/user/.tutorial_initialized
fi 

# Change the CPU counts:
CPUS=$(grep -c processor /proc/cpuinfo)
sudo xmlstarlet ed --inplace -u "config_machines/machine[@MACH='container']/MAX_TASKS_PER_NODE" -v ${CPUS} ${CESMROOT}/cime/config/cesm/machines/config_machines.xml
sudo xmlstarlet ed --inplace -u "config_machines/machine[@MACH='container']/MAX_MPITASKS_PER_NODE" -v ${CPUS} ${CESMROOT}/cime/config/cesm/machines/config_machines.xml

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec jupyter lab --ip=0.0.0.0 --NotebookApp.token='' --NotebookApp.password='' &> /tmp/jupyter_runlog.txt &
echo -e "\nWelcome to CTSM-Lab!  To connect, open your browser to:\n\t localhost:<port>"
echo -e "\nNOTE: Replace '<port>' with the port you specified in your 'docker run' command. For example, if you used the option:"
echo -e "\t        -p 9999:8888 "
echo -e "\nThen you should open the browser and go to:"
echo -e "\t localhost:9999\n\n"
wait

#exec "$@"
