name: Select a Container Image

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Push to DockerHub'
        type: boolean
        required: false
        default: false

jobs:

  build-image:
    name: Build Container Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Create containers/devenv/extras
        run: |
          sudo apt-get update
          sudo apt-get install make
          which make
          pwd
          ls
          make -C containers/tumbleweed/gui_tools
          which docker
          docker --version

      - name: Interrogate Environment
        run: |
          cat /etc/os-release
          uname -a
          env | sort
          df -h
          lscpu

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BENKIRK_DOCKERHUB_TOKEN }}

      - name: Query Docker Environment
        run: |
          which docker
          docker --version
          docker buildx ls
          docker buildx inspect
          docker buildx du

      # - name: Build
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: ${{ inputs.publish }}
      #     tags: ${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}/gh-ci-${{ inputs.os }}:latest
      #     cache-from: type=registry,ref=${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}/gh-ci-cache-${{ inputs.os }}:buildcache-${{env.INPUTS_SHA }}
      #     cache-to: type=registry,ref=${{ secrets.BENKIRK_DOCKERHUB_USERNAME }}/gh-ci-cache-${{ inputs.os }}:buildcache-${{env.INPUTS_SHA }},mode=max
      #     context: containers/tumbleweed/gui_tools
      #     file: containers/devenv/Dockerfile
      #     build-args: |
      #       BASE_OS=${{ inputs.os }}
      #       COMPILER_FAMILY=os-gcc
      #       COMPILERS_PREREQ=${{ inputs.conda && 'miniforge' || inputs.os }}
      #       FINAL_TARGET=compilers
      #     target: final
